// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vitacoin/v1/genesis.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// MerchantTier defines the tier levels for merchants
type MerchantTier int32

const (
	// MERCHANT_TIER_UNSPECIFIED is the default tier
	MerchantTierUnspecified MerchantTier = 0
	// MERCHANT_TIER_BRONZE is the bronze tier (basic features)
	MerchantTierBronze MerchantTier = 1
	// MERCHANT_TIER_SILVER is the silver tier (enhanced features)
	MerchantTierSilver MerchantTier = 2
	// MERCHANT_TIER_GOLD is the gold tier (premium features)
	MerchantTierGold MerchantTier = 3
	// MERCHANT_TIER_PLATINUM is the platinum tier (all features)
	MerchantTierPlatinum MerchantTier = 4
)

var MerchantTier_name = map[int32]string{
	0: "MERCHANT_TIER_UNSPECIFIED",
	1: "MERCHANT_TIER_BRONZE",
	2: "MERCHANT_TIER_SILVER",
	3: "MERCHANT_TIER_GOLD",
	4: "MERCHANT_TIER_PLATINUM",
}

var MerchantTier_value = map[string]int32{
	"MERCHANT_TIER_UNSPECIFIED": 0,
	"MERCHANT_TIER_BRONZE":      1,
	"MERCHANT_TIER_SILVER":      2,
	"MERCHANT_TIER_GOLD":        3,
	"MERCHANT_TIER_PLATINUM":    4,
}

func (x MerchantTier) String() string {
	return proto.EnumName(MerchantTier_name, int32(x))
}

func (MerchantTier) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28b4bcd62a4ba357, []int{0}
}

// PaymentStatus defines the status of a payment
type PaymentStatus int32

const (
	// PAYMENT_STATUS_UNSPECIFIED is the default status
	PaymentStatusUnspecified PaymentStatus = 0
	// PAYMENT_STATUS_PENDING means payment is pending confirmation
	PaymentStatusPending PaymentStatus = 1
	// PAYMENT_STATUS_COMPLETED means payment is completed
	PaymentStatusCompleted PaymentStatus = 2
	// PAYMENT_STATUS_FAILED means payment failed
	PaymentStatusFailed PaymentStatus = 3
	// PAYMENT_STATUS_REFUNDED means payment was refunded
	PaymentStatusRefunded PaymentStatus = 4
)

var PaymentStatus_name = map[int32]string{
	0: "PAYMENT_STATUS_UNSPECIFIED",
	1: "PAYMENT_STATUS_PENDING",
	2: "PAYMENT_STATUS_COMPLETED",
	3: "PAYMENT_STATUS_FAILED",
	4: "PAYMENT_STATUS_REFUNDED",
}

var PaymentStatus_value = map[string]int32{
	"PAYMENT_STATUS_UNSPECIFIED": 0,
	"PAYMENT_STATUS_PENDING":     1,
	"PAYMENT_STATUS_COMPLETED":   2,
	"PAYMENT_STATUS_FAILED":      3,
	"PAYMENT_STATUS_REFUNDED":    4,
}

func (x PaymentStatus) String() string {
	return proto.EnumName(PaymentStatus_name, int32(x))
}

func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_28b4bcd62a4ba357, []int{1}
}

// GenesisState defines the vitacoin module's genesis state.
type GenesisState struct {
	// params defines all the parameters of the module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	// merchant_list defines the list of registered merchants at genesis
	MerchantList []Merchant `protobuf:"bytes,2,rep,name=merchant_list,json=merchantList,proto3" json:"merchant_list"`
	// payment_list defines the list of payments at genesis
	PaymentList []Payment `protobuf:"bytes,3,rep,name=payment_list,json=paymentList,proto3" json:"payment_list"`
	// vault_list defines the list of time-locked vaults at genesis
	VaultList []Vault `protobuf:"bytes,4,rep,name=vault_list,json=vaultList,proto3" json:"vault_list"`
	// pool_list defines the list of reward pools at genesis
	PoolList []RewardPool `protobuf:"bytes,5,rep,name=pool_list,json=poolList,proto3" json:"pool_list"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_28b4bcd62a4ba357, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetMerchantList() []Merchant {
	if m != nil {
		return m.MerchantList
	}
	return nil
}

func (m *GenesisState) GetPaymentList() []Payment {
	if m != nil {
		return m.PaymentList
	}
	return nil
}

func (m *GenesisState) GetVaultList() []Vault {
	if m != nil {
		return m.VaultList
	}
	return nil
}

func (m *GenesisState) GetPoolList() []RewardPool {
	if m != nil {
		return m.PoolList
	}
	return nil
}

// Merchant represents a registered merchant in the e-commerce system
type Merchant struct {
	// address is the merchant's account address
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty" yaml:"address"`
	// business_name is the merchant's business name
	BusinessName string `protobuf:"bytes,2,opt,name=business_name,json=businessName,proto3" json:"business_name,omitempty"`
	// tier is the merchant's tier level (affects fees and features)
	Tier MerchantTier `protobuf:"varint,3,opt,name=tier,proto3,enum=vitacoin.v1.MerchantTier" json:"tier,omitempty"`
	// stake_amount is the amount staked by the merchant (in avita)
	StakeAmount cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=stake_amount,json=stakeAmount,proto3,customtype=cosmossdk.io/math.Int" json:"stake_amount"`
	// registration_height is the block height when merchant registered
	RegistrationHeight int64 `protobuf:"varint,5,opt,name=registration_height,json=registrationHeight,proto3" json:"registration_height,omitempty"`
	// is_active indicates if the merchant is currently active
	IsActive bool `protobuf:"varint,6,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	// total_transactions is the total number of transactions processed
	TotalTransactions uint64 `protobuf:"varint,7,opt,name=total_transactions,json=totalTransactions,proto3" json:"total_transactions,omitempty"`
	// total_volume is the total transaction volume (in avita)
	TotalVolume cosmossdk_io_math.Int `protobuf:"bytes,8,opt,name=total_volume,json=totalVolume,proto3,customtype=cosmossdk.io/math.Int" json:"total_volume"`
}

func (m *Merchant) Reset()         { *m = Merchant{} }
func (m *Merchant) String() string { return proto.CompactTextString(m) }
func (*Merchant) ProtoMessage()    {}
func (*Merchant) Descriptor() ([]byte, []int) {
	return fileDescriptor_28b4bcd62a4ba357, []int{1}
}
func (m *Merchant) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Merchant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Merchant.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Merchant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Merchant.Merge(m, src)
}
func (m *Merchant) XXX_Size() int {
	return m.Size()
}
func (m *Merchant) XXX_DiscardUnknown() {
	xxx_messageInfo_Merchant.DiscardUnknown(m)
}

var xxx_messageInfo_Merchant proto.InternalMessageInfo

func (m *Merchant) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Merchant) GetBusinessName() string {
	if m != nil {
		return m.BusinessName
	}
	return ""
}

func (m *Merchant) GetTier() MerchantTier {
	if m != nil {
		return m.Tier
	}
	return MerchantTierUnspecified
}

func (m *Merchant) GetRegistrationHeight() int64 {
	if m != nil {
		return m.RegistrationHeight
	}
	return 0
}

func (m *Merchant) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func (m *Merchant) GetTotalTransactions() uint64 {
	if m != nil {
		return m.TotalTransactions
	}
	return 0
}

// Payment represents a payment transaction in the e-commerce system
type Payment struct {
	// id is the unique payment identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// from_address is the payer's address
	FromAddress string `protobuf:"bytes,2,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	// to_address is the payee's (merchant's) address
	ToAddress string `protobuf:"bytes,3,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	// amount is the payment amount (in avita)
	Amount cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	// status is the payment status
	Status PaymentStatus `protobuf:"varint,5,opt,name=status,proto3,enum=vitacoin.v1.PaymentStatus" json:"status,omitempty"`
	// creation_height is the block height when payment was created
	CreationHeight int64 `protobuf:"varint,6,opt,name=creation_height,json=creationHeight,proto3" json:"creation_height,omitempty"`
	// completion_height is the block height when payment was completed (0 if pending)
	CompletionHeight int64 `protobuf:"varint,7,opt,name=completion_height,json=completionHeight,proto3" json:"completion_height,omitempty"`
	// memo is an optional payment memo
	Memo string `protobuf:"bytes,8,opt,name=memo,proto3" json:"memo,omitempty"`
}

func (m *Payment) Reset()         { *m = Payment{} }
func (m *Payment) String() string { return proto.CompactTextString(m) }
func (*Payment) ProtoMessage()    {}
func (*Payment) Descriptor() ([]byte, []int) {
	return fileDescriptor_28b4bcd62a4ba357, []int{2}
}
func (m *Payment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Payment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Payment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Payment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Payment.Merge(m, src)
}
func (m *Payment) XXX_Size() int {
	return m.Size()
}
func (m *Payment) XXX_DiscardUnknown() {
	xxx_messageInfo_Payment.DiscardUnknown(m)
}

var xxx_messageInfo_Payment proto.InternalMessageInfo

func (m *Payment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Payment) GetFromAddress() string {
	if m != nil {
		return m.FromAddress
	}
	return ""
}

func (m *Payment) GetToAddress() string {
	if m != nil {
		return m.ToAddress
	}
	return ""
}

func (m *Payment) GetStatus() PaymentStatus {
	if m != nil {
		return m.Status
	}
	return PaymentStatusUnspecified
}

func (m *Payment) GetCreationHeight() int64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *Payment) GetCompletionHeight() int64 {
	if m != nil {
		return m.CompletionHeight
	}
	return 0
}

func (m *Payment) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

// Vault represents a time-locked vault for loyalty rewards
type Vault struct {
	// id is the unique vault identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// owner is the vault owner's address
	Owner string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	// amount is the locked amount (in avita)
	Amount cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=amount,proto3,customtype=cosmossdk.io/math.Int" json:"amount"`
	// lock_duration is the lock duration in blocks
	LockDuration uint64 `protobuf:"varint,4,opt,name=lock_duration,json=lockDuration,proto3" json:"lock_duration,omitempty"`
	// creation_height is the block height when vault was created
	CreationHeight int64 `protobuf:"varint,5,opt,name=creation_height,json=creationHeight,proto3" json:"creation_height,omitempty"`
	// unlock_height is the block height when vault unlocks
	UnlockHeight int64 `protobuf:"varint,6,opt,name=unlock_height,json=unlockHeight,proto3" json:"unlock_height,omitempty"`
	// reward_multiplier is the reward multiplier based on lock duration
	RewardMultiplier cosmossdk_io_math.LegacyDec `protobuf:"bytes,7,opt,name=reward_multiplier,json=rewardMultiplier,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"reward_multiplier"`
}

func (m *Vault) Reset()         { *m = Vault{} }
func (m *Vault) String() string { return proto.CompactTextString(m) }
func (*Vault) ProtoMessage()    {}
func (*Vault) Descriptor() ([]byte, []int) {
	return fileDescriptor_28b4bcd62a4ba357, []int{3}
}
func (m *Vault) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Vault) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Vault.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Vault) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vault.Merge(m, src)
}
func (m *Vault) XXX_Size() int {
	return m.Size()
}
func (m *Vault) XXX_DiscardUnknown() {
	xxx_messageInfo_Vault.DiscardUnknown(m)
}

var xxx_messageInfo_Vault proto.InternalMessageInfo

func (m *Vault) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Vault) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Vault) GetLockDuration() uint64 {
	if m != nil {
		return m.LockDuration
	}
	return 0
}

func (m *Vault) GetCreationHeight() int64 {
	if m != nil {
		return m.CreationHeight
	}
	return 0
}

func (m *Vault) GetUnlockHeight() int64 {
	if m != nil {
		return m.UnlockHeight
	}
	return 0
}

// RewardPool represents a merchant loyalty reward pool
type RewardPool struct {
	// id is the unique pool identifier
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// merchant_address is the merchant's address who created the pool
	MerchantAddress string `protobuf:"bytes,2,opt,name=merchant_address,json=merchantAddress,proto3" json:"merchant_address,omitempty"`
	// total_rewards is the total rewards in the pool (in avita)
	TotalRewards cosmossdk_io_math.Int `protobuf:"bytes,3,opt,name=total_rewards,json=totalRewards,proto3,customtype=cosmossdk.io/math.Int" json:"total_rewards"`
	// distributed_rewards is the amount already distributed (in avita)
	DistributedRewards cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=distributed_rewards,json=distributedRewards,proto3,customtype=cosmossdk.io/math.Int" json:"distributed_rewards"`
	// start_height is the block height when pool started
	StartHeight int64 `protobuf:"varint,5,opt,name=start_height,json=startHeight,proto3" json:"start_height,omitempty"`
	// end_height is the block height when pool ends (0 means no end)
	EndHeight int64 `protobuf:"varint,6,opt,name=end_height,json=endHeight,proto3" json:"end_height,omitempty"`
	// is_active indicates if the pool is currently active
	IsActive bool `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
}

func (m *RewardPool) Reset()         { *m = RewardPool{} }
func (m *RewardPool) String() string { return proto.CompactTextString(m) }
func (*RewardPool) ProtoMessage()    {}
func (*RewardPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_28b4bcd62a4ba357, []int{4}
}
func (m *RewardPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RewardPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RewardPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RewardPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RewardPool.Merge(m, src)
}
func (m *RewardPool) XXX_Size() int {
	return m.Size()
}
func (m *RewardPool) XXX_DiscardUnknown() {
	xxx_messageInfo_RewardPool.DiscardUnknown(m)
}

var xxx_messageInfo_RewardPool proto.InternalMessageInfo

func (m *RewardPool) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RewardPool) GetMerchantAddress() string {
	if m != nil {
		return m.MerchantAddress
	}
	return ""
}

func (m *RewardPool) GetStartHeight() int64 {
	if m != nil {
		return m.StartHeight
	}
	return 0
}

func (m *RewardPool) GetEndHeight() int64 {
	if m != nil {
		return m.EndHeight
	}
	return 0
}

func (m *RewardPool) GetIsActive() bool {
	if m != nil {
		return m.IsActive
	}
	return false
}

func init() {
	proto.RegisterEnum("vitacoin.v1.MerchantTier", MerchantTier_name, MerchantTier_value)
	proto.RegisterEnum("vitacoin.v1.PaymentStatus", PaymentStatus_name, PaymentStatus_value)
	proto.RegisterType((*GenesisState)(nil), "vitacoin.v1.GenesisState")
	proto.RegisterType((*Merchant)(nil), "vitacoin.v1.Merchant")
	proto.RegisterType((*Payment)(nil), "vitacoin.v1.Payment")
	proto.RegisterType((*Vault)(nil), "vitacoin.v1.Vault")
	proto.RegisterType((*RewardPool)(nil), "vitacoin.v1.RewardPool")
}

func init() { proto.RegisterFile("vitacoin/v1/genesis.proto", fileDescriptor_28b4bcd62a4ba357) }

var fileDescriptor_28b4bcd62a4ba357 = []byte{
	// 1129 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x96, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0xc7, 0x2d, 0x4a, 0xfe, 0xd0, 0x48, 0x72, 0x98, 0xb5, 0x6c, 0xcb, 0x4c, 0xa3, 0x30, 0xf2,
	0xa1, 0x6a, 0x9a, 0x48, 0x8d, 0x9a, 0x7e, 0x20, 0x68, 0x81, 0x48, 0x16, 0xed, 0x08, 0x90, 0x14,
	0x81, 0x92, 0x03, 0x34, 0x17, 0x82, 0x16, 0x37, 0xf2, 0x22, 0x24, 0x57, 0x20, 0x97, 0x4a, 0xdd,
	0x27, 0x28, 0x04, 0x14, 0xe8, 0xb1, 0x17, 0x9d, 0x7a, 0xea, 0xa9, 0xbd, 0x15, 0xe8, 0x13, 0xe4,
	0x98, 0x63, 0xd1, 0x43, 0x50, 0x24, 0x6f, 0xd0, 0x27, 0x28, 0xb8, 0x24, 0x6d, 0x52, 0xf6, 0x21,
	0xb9, 0x2d, 0x67, 0xfe, 0xbf, 0xe5, 0xf0, 0xbf, 0xb3, 0x03, 0xc2, 0xde, 0x8c, 0x30, 0x7d, 0x4c,
	0x89, 0x5d, 0x9f, 0xdd, 0xaf, 0x4f, 0xb0, 0x8d, 0x5d, 0xe2, 0xd6, 0xa6, 0x0e, 0x65, 0x14, 0xe5,
	0xa2, 0x54, 0x6d, 0x76, 0x5f, 0x2a, 0x4e, 0xe8, 0x84, 0xf2, 0x78, 0xdd, 0x5f, 0x05, 0x12, 0xa9,
	0x14, 0xa7, 0xa7, 0xba, 0xa3, 0x5b, 0x21, 0x5c, 0xf9, 0x53, 0x80, 0xfc, 0x51, 0xb0, 0xdd, 0x90,
	0xe9, 0x0c, 0xa3, 0xfb, 0xb0, 0x16, 0x08, 0x4a, 0x29, 0x39, 0x55, 0xcd, 0x35, 0xb6, 0x6a, 0xb1,
	0xed, 0x6b, 0x03, 0x9e, 0x6a, 0x65, 0x5e, 0xbd, 0xb9, 0xb5, 0xa2, 0x86, 0x42, 0xf4, 0x08, 0x0a,
	0x16, 0x76, 0xc6, 0xa7, 0xba, 0xcd, 0x34, 0x93, 0xb8, 0xac, 0x24, 0xc8, 0xe9, 0x6a, 0xae, 0xb1,
	0x9d, 0x20, 0x7b, 0xa1, 0x22, 0x64, 0xf3, 0x11, 0xd1, 0x25, 0x2e, 0x43, 0xdf, 0x42, 0x7e, 0xaa,
	0x9f, 0x59, 0x38, 0xda, 0x20, 0xcd, 0x37, 0x28, 0x2e, 0xbd, 0x9a, 0x0b, 0x42, 0x3e, 0x17, 0xea,
	0x39, 0xfe, 0x15, 0xc0, 0x4c, 0xf7, 0xcc, 0x10, 0xce, 0x70, 0x18, 0x25, 0xe0, 0xa7, 0x7e, 0x3a,
	0x44, 0xb3, 0x5c, 0xcb, 0xc1, 0x87, 0x90, 0x9d, 0x52, 0x6a, 0x06, 0xdc, 0x2a, 0xe7, 0x76, 0x13,
	0x9c, 0x8a, 0x5f, 0xea, 0x8e, 0x31, 0xa0, 0xd4, 0x0c, 0xe1, 0x0d, 0x5f, 0xef, 0xb3, 0x95, 0x9f,
	0xd2, 0xb0, 0x11, 0x7d, 0x14, 0xba, 0x0b, 0xeb, 0xba, 0x61, 0x38, 0xd8, 0x0d, 0x6c, 0xcb, 0xb6,
	0xd0, 0x7f, 0x6f, 0x6e, 0x6d, 0x9e, 0xe9, 0x96, 0xf9, 0xb0, 0x12, 0x26, 0x2a, 0x6a, 0x24, 0x41,
	0xfb, 0x50, 0x38, 0xf1, 0x5c, 0x62, 0x63, 0xd7, 0xd5, 0x6c, 0xdd, 0xc2, 0x25, 0xc1, 0x67, 0xd4,
	0x7c, 0x14, 0xec, 0xeb, 0x16, 0x46, 0xf7, 0x20, 0xc3, 0x08, 0x76, 0x4a, 0x69, 0x39, 0x55, 0xdd,
	0x6c, 0xec, 0x5d, 0x69, 0xe6, 0x88, 0x60, 0x47, 0xe5, 0x32, 0xf4, 0x08, 0xf2, 0x2e, 0xd3, 0x5f,
	0x60, 0x4d, 0xb7, 0xa8, 0x67, 0xfb, 0x2e, 0xf8, 0x65, 0xdc, 0xf4, 0x8b, 0xfe, 0xe7, 0xcd, 0xad,
	0xed, 0x31, 0x75, 0x2d, 0xea, 0xba, 0xc6, 0x8b, 0x1a, 0xa1, 0x75, 0x4b, 0x67, 0xa7, 0xb5, 0x8e,
	0xcd, 0xd4, 0x1c, 0x47, 0x9a, 0x9c, 0x40, 0x75, 0xd8, 0x72, 0xf0, 0x84, 0xb8, 0xcc, 0xd1, 0x19,
	0xa1, 0xb6, 0x76, 0x8a, 0xc9, 0xe4, 0xd4, 0xb7, 0x25, 0x55, 0x4d, 0xab, 0x28, 0x9e, 0x7a, 0xcc,
	0x33, 0xe8, 0x06, 0x64, 0x89, 0xab, 0xe9, 0x63, 0x46, 0x66, 0xb8, 0xb4, 0x26, 0xa7, 0xaa, 0x1b,
	0xea, 0x06, 0x71, 0x9b, 0xfc, 0x19, 0xdd, 0x03, 0xc4, 0x28, 0xd3, 0x4d, 0x8d, 0x39, 0xba, 0xed,
	0xfa, 0x22, 0x6a, 0xbb, 0xa5, 0x75, 0x39, 0x55, 0xcd, 0xa8, 0xd7, 0x79, 0x66, 0x14, 0x4b, 0xf8,
	0xe5, 0x07, 0xf2, 0x19, 0x35, 0x3d, 0x0b, 0x97, 0x36, 0xde, 0xab, 0x7c, 0x8e, 0x3c, 0xe5, 0x44,
	0xe5, 0x0f, 0x01, 0xd6, 0xc3, 0x1e, 0x41, 0x9b, 0x20, 0x10, 0x23, 0x38, 0x09, 0x55, 0x20, 0x06,
	0xba, 0x0d, 0xf9, 0xe7, 0x0e, 0xb5, 0xb4, 0xe8, 0x8c, 0x02, 0xbf, 0x73, 0x7e, 0xac, 0x19, 0x9e,
	0xc9, 0x4d, 0x00, 0x46, 0xcf, 0x05, 0x69, 0x2e, 0xc8, 0x32, 0x1a, 0xa5, 0xbf, 0x80, 0xb5, 0x0f,
	0x31, 0x36, 0x14, 0xa3, 0x06, 0xac, 0xb9, 0x4c, 0x67, 0x9e, 0xcb, 0x6d, 0xdc, 0x6c, 0x48, 0x57,
	0xb5, 0xf4, 0x90, 0x2b, 0xd4, 0x50, 0x89, 0x3e, 0x86, 0x6b, 0x63, 0x07, 0x27, 0xce, 0x60, 0x8d,
	0x9f, 0xc1, 0x66, 0x14, 0x0e, 0xfd, 0xff, 0x14, 0xae, 0x8f, 0xa9, 0x35, 0x35, 0x71, 0x5c, 0xba,
	0xce, 0xa5, 0xe2, 0x45, 0x22, 0x14, 0x23, 0xc8, 0x58, 0xd8, 0xa2, 0x81, 0xb1, 0x2a, 0x5f, 0x57,
	0x7e, 0x13, 0x60, 0x95, 0xdf, 0x8c, 0x4b, 0x86, 0x15, 0x61, 0x95, 0xbe, 0xb4, 0xb1, 0x13, 0x3a,
	0x15, 0x3c, 0xc4, 0x4c, 0x48, 0x7f, 0x88, 0x09, 0xfb, 0x50, 0x30, 0xe9, 0xf8, 0x85, 0x66, 0x78,
	0x41, 0xfb, 0x70, 0x0b, 0x33, 0x6a, 0xde, 0x0f, 0xb6, 0xc3, 0xd8, 0x55, 0x5f, 0xbd, 0x7a, 0xe5,
	0x57, 0xef, 0x43, 0xc1, 0xb3, 0xf9, 0x7e, 0x09, 0x73, 0xf2, 0x41, 0x30, 0x14, 0x0d, 0xe0, 0xba,
	0xc3, 0xaf, 0xae, 0x66, 0x79, 0x26, 0x23, 0x53, 0xd3, 0xbf, 0x49, 0xeb, 0xbc, 0xe8, 0xfd, 0xb0,
	0xe8, 0x1b, 0x97, 0x8b, 0xee, 0xe2, 0x89, 0x3e, 0x3e, 0x6b, 0xe3, 0xb1, 0x2a, 0x06, 0x74, 0xef,
	0x1c, 0xae, 0xfc, 0x25, 0x00, 0x5c, 0x4c, 0x83, 0x4b, 0x86, 0x7d, 0x02, 0xe2, 0xf9, 0x0c, 0x4c,
	0x76, 0xd9, 0xb5, 0x28, 0x1e, 0xb5, 0x52, 0x0b, 0x0a, 0x41, 0xab, 0x07, 0xef, 0x70, 0xdf, 0xcf,
	0xcc, 0xe0, 0x7a, 0x04, 0x15, 0xb8, 0xa8, 0x0f, 0x5b, 0x86, 0x7f, 0x1d, 0xc9, 0x89, 0xc7, 0xb0,
	0x71, 0xbe, 0xd3, 0x7b, 0xf5, 0x26, 0x8a, 0x91, 0xd1, 0x7e, 0xb7, 0xf9, 0xf4, 0x70, 0x58, 0xd2,
	0xfa, 0x1c, 0x8f, 0x85, 0x96, 0xde, 0x04, 0xc0, 0xb6, 0x91, 0x34, 0x3d, 0x8b, 0x6d, 0xe3, 0xaa,
	0x61, 0xb0, 0x9e, 0x1c, 0x06, 0x77, 0x7e, 0x11, 0x20, 0x1f, 0x9f, 0x59, 0xe8, 0x21, 0xec, 0xf5,
	0x14, 0xf5, 0xe0, 0x71, 0xb3, 0x3f, 0xd2, 0x46, 0x1d, 0x45, 0xd5, 0x8e, 0xfb, 0xc3, 0x81, 0x72,
	0xd0, 0x39, 0xec, 0x28, 0x6d, 0x71, 0x45, 0xba, 0x31, 0x5f, 0xc8, 0xbb, 0x71, 0xe0, 0xd8, 0x76,
	0xa7, 0x78, 0x4c, 0x9e, 0x13, 0x6c, 0xa0, 0xcf, 0xa0, 0x98, 0x64, 0x5b, 0xea, 0x93, 0xfe, 0x33,
	0x45, 0x4c, 0x49, 0x3b, 0xf3, 0x85, 0x8c, 0xe2, 0x58, 0xcb, 0xa1, 0xf6, 0x0f, 0xf8, 0x32, 0x31,
	0xec, 0x74, 0x9f, 0x2a, 0xaa, 0x28, 0x5c, 0x26, 0x86, 0xc4, 0x9c, 0x61, 0x07, 0xdd, 0x05, 0x94,
	0x24, 0x8e, 0x9e, 0x74, 0xdb, 0x62, 0x5a, 0x2a, 0xce, 0x17, 0xb2, 0x18, 0xd7, 0x1f, 0x51, 0xd3,
	0x40, 0x0f, 0x60, 0x27, 0xa9, 0x1e, 0x74, 0x9b, 0xa3, 0x4e, 0xff, 0xb8, 0x27, 0x66, 0xa4, 0xd2,
	0x7c, 0x21, 0x17, 0xe3, 0xc4, 0xc0, 0xd4, 0x19, 0xb1, 0x3d, 0x4b, 0xca, 0xfc, 0xf8, 0x6b, 0x79,
	0xe5, 0xce, 0xef, 0x02, 0x14, 0x12, 0x73, 0x00, 0x7d, 0x03, 0xd2, 0xa0, 0xf9, 0x5d, 0x4f, 0xe9,
	0x8f, 0xb4, 0xe1, 0xa8, 0x39, 0x3a, 0x1e, 0x2e, 0x99, 0xf3, 0xd1, 0x7c, 0x21, 0x97, 0x12, 0x48,
	0xdc, 0x9d, 0x07, 0xb0, 0xb3, 0x44, 0x0f, 0x94, 0x7e, 0xbb, 0xd3, 0x3f, 0x12, 0x53, 0x41, 0x2d,
	0x09, 0x72, 0x80, 0x6d, 0x83, 0xd8, 0x13, 0xf4, 0x35, 0x94, 0x96, 0xa8, 0x83, 0x27, 0xbd, 0x41,
	0x57, 0x19, 0x29, 0x6d, 0x51, 0x90, 0xa4, 0xf9, 0x42, 0xde, 0x49, 0x70, 0x07, 0xc1, 0x78, 0xc1,
	0x06, 0x6a, 0xc0, 0xf6, 0x12, 0x79, 0xd8, 0xec, 0x74, 0x15, 0xdf, 0xac, 0xdd, 0xf9, 0x42, 0xde,
	0x4a, 0x60, 0x87, 0x3a, 0x31, 0xb1, 0x81, 0xbe, 0x84, 0xdd, 0x25, 0x46, 0x55, 0x0e, 0x8f, 0xfb,
	0x6d, 0xa5, 0x2d, 0x66, 0xa4, 0xbd, 0xf9, 0x42, 0xde, 0x4e, 0x4e, 0x46, 0xfc, 0xdc, 0xb3, 0x0d,
	0x6c, 0x04, 0x8e, 0xb5, 0x8e, 0x5e, 0xbd, 0x2d, 0xa7, 0x5e, 0xbf, 0x2d, 0xa7, 0xfe, 0x7d, 0x5b,
	0x4e, 0xfd, 0xfc, 0xae, 0xbc, 0xf2, 0xfa, 0x5d, 0x79, 0xe5, 0xef, 0x77, 0xe5, 0x95, 0x67, 0xf7,
	0x26, 0x84, 0x9d, 0x7a, 0x27, 0xb5, 0x31, 0xb5, 0xea, 0x17, 0x7f, 0x3c, 0xd1, 0xe2, 0xfb, 0x8b,
	0x25, 0x3b, 0x9b, 0x62, 0xf7, 0x64, 0x8d, 0xff, 0x02, 0x7d, 0xfe, 0x7f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x69, 0x72, 0x0a, 0x55, 0x5c, 0x09, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PoolList) > 0 {
		for iNdEx := len(m.PoolList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PoolList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.VaultList) > 0 {
		for iNdEx := len(m.VaultList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VaultList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PaymentList) > 0 {
		for iNdEx := len(m.PaymentList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PaymentList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.MerchantList) > 0 {
		for iNdEx := len(m.MerchantList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MerchantList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Merchant) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Merchant) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Merchant) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.TotalVolume.Size()
		i -= size
		if _, err := m.TotalVolume.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.TotalTransactions != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.TotalTransactions))
		i--
		dAtA[i] = 0x38
	}
	if m.IsActive {
		i--
		if m.IsActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.RegistrationHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RegistrationHeight))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.StakeAmount.Size()
		i -= size
		if _, err := m.StakeAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.Tier != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Tier))
		i--
		dAtA[i] = 0x18
	}
	if len(m.BusinessName) > 0 {
		i -= len(m.BusinessName)
		copy(dAtA[i:], m.BusinessName)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.BusinessName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Payment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Payment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Payment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x42
	}
	if m.CompletionHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CompletionHeight))
		i--
		dAtA[i] = 0x38
	}
	if m.CreationHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CreationHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.Status != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if len(m.ToAddress) > 0 {
		i -= len(m.ToAddress)
		copy(dAtA[i:], m.ToAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.ToAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.FromAddress) > 0 {
		i -= len(m.FromAddress)
		copy(dAtA[i:], m.FromAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.FromAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Vault) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Vault) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Vault) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.RewardMultiplier.Size()
		i -= size
		if _, err := m.RewardMultiplier.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	if m.UnlockHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.UnlockHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.CreationHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.CreationHeight))
		i--
		dAtA[i] = 0x28
	}
	if m.LockDuration != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.LockDuration))
		i--
		dAtA[i] = 0x20
	}
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RewardPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RewardPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RewardPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsActive {
		i--
		if m.IsActive {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.EndHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.EndHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.StartHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.StartHeight))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.DistributedRewards.Size()
		i -= size
		if _, err := m.DistributedRewards.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.TotalRewards.Size()
		i -= size
		if _, err := m.TotalRewards.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.MerchantAddress) > 0 {
		i -= len(m.MerchantAddress)
		copy(dAtA[i:], m.MerchantAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.MerchantAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.MerchantList) > 0 {
		for _, e := range m.MerchantList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PaymentList) > 0 {
		for _, e := range m.PaymentList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.VaultList) > 0 {
		for _, e := range m.VaultList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PoolList) > 0 {
		for _, e := range m.PoolList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func (m *Merchant) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.BusinessName)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Tier != 0 {
		n += 1 + sovGenesis(uint64(m.Tier))
	}
	l = m.StakeAmount.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.RegistrationHeight != 0 {
		n += 1 + sovGenesis(uint64(m.RegistrationHeight))
	}
	if m.IsActive {
		n += 2
	}
	if m.TotalTransactions != 0 {
		n += 1 + sovGenesis(uint64(m.TotalTransactions))
	}
	l = m.TotalVolume.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *Payment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.FromAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.ToAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.Status != 0 {
		n += 1 + sovGenesis(uint64(m.Status))
	}
	if m.CreationHeight != 0 {
		n += 1 + sovGenesis(uint64(m.CreationHeight))
	}
	if m.CompletionHeight != 0 {
		n += 1 + sovGenesis(uint64(m.CompletionHeight))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *Vault) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.LockDuration != 0 {
		n += 1 + sovGenesis(uint64(m.LockDuration))
	}
	if m.CreationHeight != 0 {
		n += 1 + sovGenesis(uint64(m.CreationHeight))
	}
	if m.UnlockHeight != 0 {
		n += 1 + sovGenesis(uint64(m.UnlockHeight))
	}
	l = m.RewardMultiplier.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *RewardPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.MerchantAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.TotalRewards.Size()
	n += 1 + l + sovGenesis(uint64(l))
	l = m.DistributedRewards.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if m.StartHeight != 0 {
		n += 1 + sovGenesis(uint64(m.StartHeight))
	}
	if m.EndHeight != 0 {
		n += 1 + sovGenesis(uint64(m.EndHeight))
	}
	if m.IsActive {
		n += 2
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantList = append(m.MerchantList, Merchant{})
			if err := m.MerchantList[len(m.MerchantList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PaymentList = append(m.PaymentList, Payment{})
			if err := m.PaymentList[len(m.PaymentList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VaultList = append(m.VaultList, Vault{})
			if err := m.VaultList[len(m.VaultList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolList = append(m.PoolList, RewardPool{})
			if err := m.PoolList[len(m.PoolList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Merchant) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Merchant: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Merchant: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BusinessName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BusinessName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tier", wireType)
			}
			m.Tier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Tier |= MerchantTier(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakeAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.StakeAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistrationHeight", wireType)
			}
			m.RegistrationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistrationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActive = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalTransactions", wireType)
			}
			m.TotalTransactions = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TotalTransactions |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalVolume", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalVolume.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Payment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Payment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Payment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FromAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FromAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ToAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ToAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= PaymentStatus(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeight", wireType)
			}
			m.CreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CompletionHeight", wireType)
			}
			m.CompletionHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CompletionHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Vault) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Vault: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Vault: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockDuration", wireType)
			}
			m.LockDuration = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LockDuration |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationHeight", wireType)
			}
			m.CreationHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnlockHeight", wireType)
			}
			m.UnlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.UnlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RewardMultiplier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RewardMultiplier.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RewardPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RewardPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RewardPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MerchantAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TotalRewards", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TotalRewards.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistributedRewards", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.DistributedRewards.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartHeight", wireType)
			}
			m.StartHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.StartHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndHeight", wireType)
			}
			m.EndHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsActive", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsActive = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
