// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vitacoin/v1/params.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the vitacoin module.
// These parameters control the e-commerce payment system behavior.
type Params struct {
	// min_gas_price is the minimum gas price for transactions (in avita)
	MinGasPrice cosmossdk_io_math.LegacyDec `protobuf:"bytes,1,opt,name=min_gas_price,json=minGasPrice,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"min_gas_price"`
	// transaction_fee_percent is the percentage fee charged on each transaction (0-100)
	// Example: 0.5 = 0.5% fee
	TransactionFeePercent cosmossdk_io_math.LegacyDec `protobuf:"bytes,2,opt,name=transaction_fee_percent,json=transactionFeePercent,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"transaction_fee_percent"`
	// merchant_fee_discount is the discount percentage for verified merchants (0-100)
	// Example: 50.0 = 50% discount on transaction fees
	MerchantFeeDiscount cosmossdk_io_math.LegacyDec `protobuf:"bytes,3,opt,name=merchant_fee_discount,json=merchantFeeDiscount,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"merchant_fee_discount"`
	// max_transaction_amount is the maximum allowed transaction amount (in avita)
	// 0 means no limit
	MaxTransactionAmount cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=max_transaction_amount,json=maxTransactionAmount,proto3,customtype=cosmossdk.io/math.Int" json:"max_transaction_amount"`
	// payment_timeout_blocks is the number of blocks before a pending payment expires
	PaymentTimeoutBlocks uint64 `protobuf:"varint,5,opt,name=payment_timeout_blocks,json=paymentTimeoutBlocks,proto3" json:"payment_timeout_blocks,omitempty"`
	// merchant_registration_fee is the fee to register as a merchant (in avita)
	MerchantRegistrationFee cosmossdk_io_math.Int `protobuf:"bytes,6,opt,name=merchant_registration_fee,json=merchantRegistrationFee,proto3,customtype=cosmossdk.io/math.Int" json:"merchant_registration_fee"`
	// enable_merchant_loyalty defines whether merchant loyalty rewards are enabled
	EnableMerchantLoyalty bool `protobuf:"varint,7,opt,name=enable_merchant_loyalty,json=enableMerchantLoyalty,proto3" json:"enable_merchant_loyalty,omitempty"`
	// loyalty_reward_percent is the percentage of transaction value given as loyalty points (0-100)
	LoyaltyRewardPercent cosmossdk_io_math.LegacyDec `protobuf:"bytes,8,opt,name=loyalty_reward_percent,json=loyaltyRewardPercent,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"loyalty_reward_percent"`
	// min_merchant_stake is the minimum amount a merchant must stake (in avita)
	MinMerchantStake cosmossdk_io_math.Int `protobuf:"bytes,9,opt,name=min_merchant_stake,json=minMerchantStake,proto3,customtype=cosmossdk.io/math.Int" json:"min_merchant_stake"`
	// enable_instant_settlement defines whether instant settlement is enabled for payments
	EnableInstantSettlement bool `protobuf:"varint,10,opt,name=enable_instant_settlement,json=enableInstantSettlement,proto3" json:"enable_instant_settlement,omitempty"`
	// fee_burn_percent is the percentage of transaction fees that are burned (0-100)
	// Implements deflationary tokenomics - default 25%
	FeeBurnPercent cosmossdk_io_math.LegacyDec `protobuf:"bytes,11,opt,name=fee_burn_percent,json=feeBurnPercent,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"fee_burn_percent"`
	// fee_validator_percent is the percentage of transaction fees sent to validators (0-100)
	// Default 50% - sent to FeeCollector for distribution
	FeeValidatorPercent cosmossdk_io_math.LegacyDec `protobuf:"bytes,12,opt,name=fee_validator_percent,json=feeValidatorPercent,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"fee_validator_percent"`
	// fee_treasury_percent is the percentage of transaction fees sent to treasury (0-100)
	// Default 25% - controlled by governance
	FeeTreasuryPercent cosmossdk_io_math.LegacyDec `protobuf:"bytes,13,opt,name=fee_treasury_percent,json=feeTreasuryPercent,proto3,customtype=cosmossdk.io/math.LegacyDec" json:"fee_treasury_percent"`
	// min_protocol_fee is the minimum protocol fee charged per payment (in avita)
	// Default 0.001 VITA (1e15 avita) - prevents dust attacks
	MinProtocolFee cosmossdk_io_math.Int `protobuf:"bytes,14,opt,name=min_protocol_fee,json=minProtocolFee,proto3,customtype=cosmossdk.io/math.Int" json:"min_protocol_fee"`
	// max_protocol_fee is the maximum protocol fee charged per payment (in avita)
	// Default 100 VITA (1e20 avita) - prevents accidental overpayment
	MaxProtocolFee cosmossdk_io_math.Int `protobuf:"bytes,15,opt,name=max_protocol_fee,json=maxProtocolFee,proto3,customtype=cosmossdk.io/math.Int" json:"max_protocol_fee"`
	// burn_cap_supply is the target minimum supply (in avita) where burning stops
	// Default 500M VITA (5e26 avita) - prevents over-deflation
	BurnCapSupply cosmossdk_io_math.Int `protobuf:"bytes,16,opt,name=burn_cap_supply,json=burnCapSupply,proto3,customtype=cosmossdk.io/math.Int" json:"burn_cap_supply"`
	// paused_fee_collection is an emergency flag to pause protocol fee collection
	// Can only be set by governance
	PausedFeeCollection bool `protobuf:"varint,17,opt,name=paused_fee_collection,json=pausedFeeCollection,proto3" json:"paused_fee_collection,omitempty"`
	// paused_fee_distribution is an emergency flag to pause fee distribution
	// Can only be set by governance
	PausedFeeDistribution bool `protobuf:"varint,18,opt,name=paused_fee_distribution,json=pausedFeeDistribution,proto3" json:"paused_fee_distribution,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_311cbd1d4eee2c4b, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetPaymentTimeoutBlocks() uint64 {
	if m != nil {
		return m.PaymentTimeoutBlocks
	}
	return 0
}

func (m *Params) GetEnableMerchantLoyalty() bool {
	if m != nil {
		return m.EnableMerchantLoyalty
	}
	return false
}

func (m *Params) GetEnableInstantSettlement() bool {
	if m != nil {
		return m.EnableInstantSettlement
	}
	return false
}

func (m *Params) GetPausedFeeCollection() bool {
	if m != nil {
		return m.PausedFeeCollection
	}
	return false
}

func (m *Params) GetPausedFeeDistribution() bool {
	if m != nil {
		return m.PausedFeeDistribution
	}
	return false
}

func init() {
	proto.RegisterType((*Params)(nil), "vitacoin.v1.Params")
}

func init() { proto.RegisterFile("vitacoin/v1/params.proto", fileDescriptor_311cbd1d4eee2c4b) }

var fileDescriptor_311cbd1d4eee2c4b = []byte{
	// 534 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0x4f, 0x6b, 0x1a, 0x41,
	0x18, 0xc6, 0xdd, 0x36, 0x35, 0xc9, 0x48, 0x4b, 0x98, 0xfa, 0x67, 0x4d, 0x61, 0x95, 0x9e, 0x84,
	0x12, 0x45, 0x5a, 0x7a, 0xc8, 0xad, 0x22, 0x06, 0x21, 0x05, 0xd9, 0xa4, 0x87, 0xb6, 0x87, 0x65,
	0x1c, 0xdf, 0xac, 0x83, 0xce, 0x8c, 0xcc, 0x8c, 0x56, 0xbf, 0x45, 0x8f, 0x3d, 0xf6, 0x43, 0xf4,
	0x43, 0xe4, 0x54, 0x42, 0x4f, 0xa5, 0x87, 0x50, 0xf4, 0x8b, 0x94, 0x9d, 0xfd, 0xa3, 0xd0, 0x53,
	0xbc, 0xbd, 0xfa, 0xbc, 0xfb, 0x7b, 0xe6, 0x79, 0xe7, 0x65, 0x90, 0xbb, 0x60, 0x86, 0x50, 0xc9,
	0x44, 0x6b, 0xd1, 0x6e, 0xcd, 0x88, 0x22, 0x5c, 0x37, 0x67, 0x4a, 0x1a, 0x89, 0x0b, 0xa9, 0xd2,
	0x5c, 0xb4, 0x4f, 0x8b, 0xa1, 0x0c, 0xa5, 0xfd, 0xbf, 0x15, 0x55, 0x71, 0xcb, 0x69, 0x95, 0x4a,
	0xcd, 0xa5, 0x0e, 0x62, 0x21, 0xfe, 0x11, 0x4b, 0x2f, 0x7f, 0x1e, 0xa2, 0xfc, 0xc0, 0xe2, 0xf0,
	0x07, 0xf4, 0x94, 0x33, 0x11, 0x84, 0x24, 0x6a, 0x64, 0x14, 0x5c, 0xa7, 0xee, 0x34, 0x8e, 0x3b,
	0xed, 0xdb, 0xfb, 0x5a, 0xee, 0xcf, 0x7d, 0xed, 0x45, 0xfc, 0x9d, 0x1e, 0x4d, 0x9a, 0x4c, 0xb6,
	0x38, 0x31, 0xe3, 0xe6, 0x25, 0x84, 0x84, 0xae, 0xba, 0x40, 0x7f, 0xfd, 0x38, 0x43, 0x09, 0xb6,
	0x0b, 0xd4, 0x2f, 0x70, 0x26, 0x2e, 0x88, 0x1e, 0x44, 0x14, 0xcc, 0x50, 0xc5, 0x28, 0x22, 0x34,
	0xa1, 0x86, 0x49, 0x11, 0xdc, 0x00, 0x04, 0x33, 0x50, 0x14, 0x84, 0x71, 0x1f, 0xed, 0x6b, 0x50,
	0xda, 0x21, 0xf6, 0x00, 0x06, 0x31, 0x0f, 0x03, 0x2a, 0x71, 0x50, 0x74, 0x4c, 0x84, 0xb1, 0x3e,
	0x23, 0xa6, 0xa9, 0x9c, 0x0b, 0xe3, 0x3e, 0xde, 0xd7, 0xe8, 0x79, 0xca, 0xeb, 0x01, 0x74, 0x13,
	0x1a, 0x26, 0xa8, 0xcc, 0xc9, 0x32, 0xd8, 0x4d, 0x45, 0xb8, 0xf5, 0x39, 0xb0, 0x3e, 0xaf, 0x12,
	0x9f, 0xd2, 0xff, 0x3e, 0x7d, 0x61, 0x76, 0x1c, 0xfa, 0xc2, 0xf8, 0x45, 0x4e, 0x96, 0xd7, 0x5b,
	0xd2, 0x3b, 0x0b, 0xc2, 0x6f, 0x50, 0x79, 0x46, 0x56, 0x1c, 0x84, 0x09, 0x0c, 0xe3, 0x20, 0xe7,
	0x26, 0x18, 0x4e, 0x25, 0x9d, 0x68, 0xf7, 0x49, 0xdd, 0x69, 0x1c, 0xf8, 0xc5, 0x44, 0xbd, 0x8e,
	0xc5, 0x8e, 0xd5, 0x70, 0x88, 0xaa, 0x59, 0x7e, 0x05, 0x21, 0xd3, 0x46, 0x91, 0x74, 0xe8, 0x6e,
	0xfe, 0xe1, 0x67, 0xab, 0xa4, 0x34, 0x7f, 0x07, 0xd6, 0x03, 0xc0, 0x6f, 0x51, 0x05, 0x04, 0x19,
	0x4e, 0x21, 0xc8, 0xfc, 0xa6, 0x72, 0x45, 0xa6, 0x66, 0xe5, 0x1e, 0xd6, 0x9d, 0xc6, 0x91, 0x5f,
	0x8a, 0xe5, 0xf7, 0x89, 0x7a, 0x19, 0x8b, 0x38, 0x44, 0xe5, 0xa4, 0x2f, 0x50, 0xf0, 0x85, 0xa8,
	0x51, 0xb6, 0x0a, 0x47, 0xfb, 0xde, 0x50, 0x31, 0x01, 0xfa, 0x96, 0x97, 0x6e, 0xc2, 0x47, 0x84,
	0xa3, 0x5d, 0xce, 0x4e, 0xa7, 0x0d, 0x99, 0x80, 0x7b, 0xfc, 0xf0, 0x11, 0x9c, 0x70, 0x26, 0xd2,
	0x14, 0x57, 0x11, 0x04, 0x9f, 0xa3, 0x6a, 0x92, 0x9d, 0x09, 0x6d, 0x2c, 0x1c, 0x8c, 0x99, 0x42,
	0x74, 0x1d, 0x2e, 0xb2, 0xe9, 0x93, 0xe1, 0xf4, 0x63, 0xfd, 0x2a, 0x93, 0xf1, 0x67, 0x74, 0x12,
	0xed, 0xe5, 0x70, 0xae, 0x44, 0x96, 0xbc, 0xb0, 0x6f, 0xf2, 0x67, 0x37, 0x00, 0x9d, 0xb9, 0x12,
	0x49, 0xe6, 0xf3, 0x83, 0x6f, 0xdf, 0x6b, 0xb9, 0xce, 0xc5, 0xed, 0xda, 0x73, 0xee, 0xd6, 0x9e,
	0xf3, 0x77, 0xed, 0x39, 0x5f, 0x37, 0x5e, 0xee, 0x6e, 0xe3, 0xe5, 0x7e, 0x6f, 0xbc, 0xdc, 0xa7,
	0xb3, 0x90, 0x99, 0xf1, 0x7c, 0xd8, 0xa4, 0x92, 0xb7, 0xb6, 0xaf, 0x49, 0x5a, 0x2c, 0xb7, 0xa5,
	0x59, 0xcd, 0x40, 0x0f, 0xf3, 0xf6, 0x81, 0x78, 0xfd, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xde, 0x6b,
	0xde, 0xb6, 0x7a, 0x04, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.FeeBurnPercent.Size()
		i -= size
		if _, err := m.FeeBurnPercent.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if m.EnableInstantSettlement {
		i--
		if m.EnableInstantSettlement {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x50
	}
	{
		size := m.MinMerchantStake.Size()
		i -= size
		if _, err := m.MinMerchantStake.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x4a
	{
		size := m.LoyaltyRewardPercent.Size()
		i -= size
		if _, err := m.LoyaltyRewardPercent.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	if m.EnableMerchantLoyalty {
		i--
		if m.EnableMerchantLoyalty {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.MerchantRegistrationFee.Size()
		i -= size
		if _, err := m.MerchantRegistrationFee.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if m.PaymentTimeoutBlocks != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.PaymentTimeoutBlocks))
		i--
		dAtA[i] = 0x28
	}
	{
		size := m.MaxTransactionAmount.Size()
		i -= size
		if _, err := m.MaxTransactionAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.MerchantFeeDiscount.Size()
		i -= size
		if _, err := m.MerchantFeeDiscount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.TransactionFeePercent.Size()
		i -= size
		if _, err := m.TransactionFeePercent.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.MinGasPrice.Size()
		i -= size
		if _, err := m.MinGasPrice.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinGasPrice.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.TransactionFeePercent.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MerchantFeeDiscount.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MaxTransactionAmount.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.PaymentTimeoutBlocks != 0 {
		n += 1 + sovParams(uint64(m.PaymentTimeoutBlocks))
	}
	l = m.MerchantRegistrationFee.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.EnableMerchantLoyalty {
		n += 2
	}
	l = m.LoyaltyRewardPercent.Size()
	n += 1 + l + sovParams(uint64(l))
	l = m.MinMerchantStake.Size()
	n += 1 + l + sovParams(uint64(l))
	if m.EnableInstantSettlement {
		n += 2
	}
	l = m.FeeBurnPercent.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinGasPrice", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinGasPrice.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransactionFeePercent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TransactionFeePercent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantFeeDiscount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MerchantFeeDiscount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxTransactionAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaxTransactionAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PaymentTimeoutBlocks", wireType)
			}
			m.PaymentTimeoutBlocks = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PaymentTimeoutBlocks |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MerchantRegistrationFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MerchantRegistrationFee.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableMerchantLoyalty", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableMerchantLoyalty = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LoyaltyRewardPercent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LoyaltyRewardPercent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinMerchantStake", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinMerchantStake.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EnableInstantSettlement", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.EnableInstantSettlement = bool(v != 0)
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeBurnPercent", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeBurnPercent.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
